on: push

# 工作集合
jobs:
  # 自定义工作名称
  npm-build:
    runs-on: ubuntu-latest # 工作环境 windows-latest
    steps: # 工作步骤
      - run: pwd
      - run: npm --version
      - run: npm install
      - run: npm run build